const BACKEND_URL='http://127.0.0.1:8000';
const API_URL=`${BACKEND_URL}/generate`;
const ATTACHMENT_API_URL=`${BACKEND_URL}/generate-with-attachment`;
const PREVIEW_ATTACHMENT_API_URL=`${BACKEND_URL}/preview-attachment`;
const CONFIG_URL=`${BACKEND_URL}/config`;
let runtimeConfig={use_ai:false,provider:'local',model:''};
let loadingTimer=null;
let attachmentPreviewState={title:'Attachment Preview',content:'No attachment selected.',fileKey:'',loaded:false};
function escapeHtml(value){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')}
function formatFileSize(bytes){if(!Number.isFinite(bytes)||bytes<1024)return `${bytes||0} B`;if(bytes<1024*1024)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/(1024*1024)).toFixed(1)} MB`}
function setAttachmentPreviewState(title,content,fileKey='',loaded=false){attachmentPreviewState={title,content,fileKey,loaded};document.getElementById('attachmentPreviewTitle').textContent=title;document.getElementById('attachmentPreviewBody').textContent=content}
async function openAttachmentPreview(){const modal=document.getElementById('attachmentPreviewModal');const input=document.getElementById('attachment');const previewButton=document.getElementById('previewAttachmentBtn');const [file]=input.files;modal.classList.remove('preview-modal-hidden');modal.setAttribute('aria-hidden','false');if(!file){setAttachmentPreviewState('Attachment Preview','No attachment selected.');return}const fileKey=`${file.name}:${file.size}:${file.lastModified}`;if(attachmentPreviewState.loaded&&attachmentPreviewState.fileKey===fileKey){setAttachmentPreviewState(attachmentPreviewState.title,attachmentPreviewState.content,fileKey,true);return}setAttachmentPreviewState(`Preview: ${file.name}`,'Loading preview...',fileKey,false);previewButton.disabled=true;try{const formData=new FormData();formData.append('attachment',file);const response=await fetch(PREVIEW_ATTACHMENT_API_URL,{method:'POST',body:formData});if(!response.ok){const errorBody=await response.json().catch(()=>null);throw new Error(errorBody?.detail||`Preview error: ${response.status}`)}const data=await response.json();const suffix=data.truncated?'\n\nPreview truncated for display.':'';setAttachmentPreviewState(`Preview: ${data.filename}`,`${data.preview||'No readable text was found in this attachment.'}${suffix}`,fileKey,true)}catch(error){setAttachmentPreviewState(`Preview: ${file.name}`,error.message||'Unable to preview this attachment.',fileKey,false)}finally{previewButton.disabled=false}}
function closeAttachmentPreview(){const modal=document.getElementById('attachmentPreviewModal');modal.classList.add('preview-modal-hidden');modal.setAttribute('aria-hidden','true')}
function resetAttachmentPreview(){const meta=document.getElementById('attachmentMeta');const previewButton=document.getElementById('previewAttachmentBtn');const removeButton=document.getElementById('removeAttachmentBtn');meta.textContent='No attachment selected. You can generate with the form only.';meta.className='attachment-meta attachment-meta-empty';previewButton.classList.add('attachment-preview-trigger-hidden');removeButton.classList.add('attachment-preview-trigger-hidden');previewButton.disabled=false;removeButton.disabled=false;setAttachmentPreviewState('Attachment Preview','No attachment selected.','',false)}
function updateAttachmentPreview(){const input=document.getElementById('attachment');const meta=document.getElementById('attachmentMeta');const previewButton=document.getElementById('previewAttachmentBtn');const removeButton=document.getElementById('removeAttachmentBtn');const [file]=input.files;if(!file){resetAttachmentPreview();return}meta.textContent=`Selected: ${file.name} (${formatFileSize(file.size)})`;meta.className='attachment-meta';previewButton.classList.remove('attachment-preview-trigger-hidden');removeButton.classList.remove('attachment-preview-trigger-hidden');previewButton.disabled=false;removeButton.disabled=false;setAttachmentPreviewState(`Preview: ${file.name}`,'Click Preview to extract and view this attachment.',`${file.name}:${file.size}:${file.lastModified}`,false)}
function removeAttachment(){document.getElementById('attachment').value='';closeAttachmentPreview();resetAttachmentPreview()}
function setStatus(message,isError=false,isLoading=false){const s=document.getElementById('status');s.textContent=message;s.style.color=isError?'#dc2626':'#0f766e';s.classList.toggle('loading',isLoading)}
function clearFieldErrors(){['title','domain','story','criteria','attachment'].forEach(id=>document.getElementById(id).classList.remove('field-error'))}
function validatePayload(payload,hasAttachment){const missing=[];clearFieldErrors();if(hasAttachment)return missing;const fields=[['title','Ticket Title'],['domain','Domain'],['story','User Story / Requirement'],['criteria','Acceptance Criteria']];fields.forEach(([key,label])=>{if(!String(payload[key]??'').trim()){missing.push(label);document.getElementById(key).classList.add('field-error')}});return missing}
function startLoadingStatus(baseMessage){const s=document.getElementById('status');let step=0;clearInterval(loadingTimer);setStatus(baseMessage,false,true);loadingTimer=setInterval(()=>{step=(step+1)%4;s.textContent=`${baseMessage}${'.'.repeat(step)}`},400)}
function stopLoadingStatus(){clearInterval(loadingTimer);loadingTimer=null;document.getElementById('status').classList.remove('loading')}
function formatProviderName(provider){if(provider==='openai')return 'OpenAI';if(provider==='azure')return 'Azure';return 'Local'}
function getActiveModelLabel(){if(!runtimeConfig.use_ai)return 'Local rules';return runtimeConfig.model||'Configured model unavailable'}
function updateModelBadge(){const provider=runtimeConfig.use_ai?runtimeConfig.provider:'local';const badge=document.getElementById('modelBadge');badge.textContent=`Model: ${getActiveModelLabel()}`;badge.className=`model-badge model-badge-${provider}`}
function updateAiSignal(isLoading=false){const provider=runtimeConfig.use_ai?runtimeConfig.provider:'local';const signal=document.getElementById('aiSignal');const title=document.getElementById('aiSignalTitle');const detail=document.getElementById('aiSignalDetail');const modelLabel=getActiveModelLabel();signal.className=`ai-signal ai-signal-${provider}${isLoading?' ai-signal-live':''}`;if(provider==='openai'){title.textContent=isLoading?'OpenAI response in progress':'OpenAI active';detail.textContent=isLoading?`Waiting for ${modelLabel} to return structured JSON output`:`Using OpenAI model ${modelLabel}`}else if(provider==='azure'){title.textContent=isLoading?'Azure AI response in progress':'Azure AI active';detail.textContent=isLoading?`Waiting for Azure deployment ${modelLabel} to return structured JSON output`:`Using Azure deployment ${modelLabel}`}else{title.textContent=isLoading?'Local generation in progress':'Local generator';detail.textContent=isLoading?'Producing rule-based QA draft without cloud AI':'Rule-based fallback mode'}}
function updateProviderBadge(){const badge=document.getElementById('providerBadge');const provider=runtimeConfig.use_ai?runtimeConfig.provider:'local';badge.textContent=`Provider: ${formatProviderName(provider)}`;badge.className=`provider-badge provider-${provider}`}
async function loadRuntimeConfig(){try{const response=await fetch(CONFIG_URL);if(!response.ok)throw new Error(`Config error: ${response.status}`);runtimeConfig=await response.json()}catch(error){runtimeConfig={use_ai:false,provider:'local',model:''}}updateProviderBadge();updateModelBadge();updateAiSignal(false)}
function bulletList(items){return items.map(i=>`- ${i}`).join('\n')}
function renderList(items){return `<ul class="output-list">${items.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul>`}
function renderTestCases(testCases){return `<div class="test-case-grid">${testCases.map(tc=>`<article class="test-case-card"><div class="test-case-head"><div><h4>${escapeHtml(tc.id)}: ${escapeHtml(tc.title)}</h4><p>${escapeHtml(tc.type)} test case</p></div><div class="test-case-meta"><span>${escapeHtml(tc.priority)}</span><span>${escapeHtml(tc.type)}</span></div></div><div class="output-subsection"><h5>Preconditions</h5>${renderList(tc.preconditions)}</div><div class="output-subsection"><h5>Steps</h5><ol class="output-steps">${tc.steps.map(step=>`<li>${escapeHtml(step)}</li>`).join('')}</ol></div><div class="output-subsection"><h5>Expected Result</h5><p>${escapeHtml(tc.expected_result)}</p></div></article>`).join('')}</div>`}
function renderApiCoverage(items){return `<div class="api-grid">${items.map(item=>`<article class="api-card"><div class="api-method">${escapeHtml(item.method)}</div><div class="api-endpoint">${escapeHtml(item.endpoint)}</div><p>${escapeHtml(item.validation)}</p><span class="api-status">Expected: ${escapeHtml(item.expected_status)}</span></article>`).join('')}</div>`}
function renderAcceptanceMapping(items){return `<div class="mapping-grid">${items.map(item=>`<article class="mapping-card"><h4>${escapeHtml(item.criterion)}</h4><p><strong>Covered By:</strong> ${escapeHtml((item.covered_by||[]).join(', ')||'Not mapped')}</p><p><strong>Notes:</strong> ${escapeHtml(item.notes||'None')}</p></article>`).join('')}</div>`}
function renderCoverageScore(score){return `<div class="coverage-grid"><article class="coverage-card coverage-overall"><span class="coverage-label">Overall</span><strong>${escapeHtml(score.overall)}/100</strong></article><article class="coverage-card"><span class="coverage-label">Acceptance Criteria</span><strong>${escapeHtml(score.acceptance_criteria)}/100</strong></article><article class="coverage-card"><span class="coverage-label">Negative Paths</span><strong>${escapeHtml(score.negative_paths)}/100</strong></article><article class="coverage-card"><span class="coverage-label">Integration</span><strong>${escapeHtml(score.integration)}/100</strong></article></div><p class="coverage-notes">${escapeHtml(score.notes||'')}</p>`}
function renderSection(title,content,accent=''){return `<section class="output-section ${accent}"><h3>${escapeHtml(title)}</h3>${content}</section>`}
function formatPackage(data){return [
renderSection('Requirement Summary',`<p>${escapeHtml(data.requirement_summary)}</p>`,'summary-section'),
renderSection('Coverage Score',renderCoverageScore(data.coverage_score),'coverage-section'),
renderSection('Functional Scenarios',renderList(data.functional_scenarios),'scenarios-section'),
renderSection('Negative Scenarios',renderList(data.negative_scenarios),'scenarios-section'),
renderSection('Test Cases',renderTestCases(data.test_cases),'test-section'),
renderSection('API Coverage',renderApiCoverage(data.api_coverage),'api-section'),
renderSection('Assumptions',renderList((data.assumptions||[]).length?data.assumptions:['None identified'])),
renderSection('Open Questions',renderList((data.open_questions||[]).length?data.open_questions:['None identified'])),
renderSection('Acceptance Criteria Mapping',(data.acceptance_criteria_mapping||[]).length?renderAcceptanceMapping(data.acceptance_criteria_mapping):'<p>No acceptance criteria mapping available.</p>','mapping-section'),
renderSection('Requirement Gaps',renderList(data.requirement_gaps)),
renderSection('Automation Recommendation',`<p>${escapeHtml(data.automation_recommendation)}</p>`),
renderSection('Risk Assessment',`<div class="risk-strip"><span class="risk-score">${escapeHtml(data.risk_score)}</span><p>${escapeHtml(data.risk_reason)}</p></div>`,'risk-section'),
renderSection('Business Impact',`<p>${escapeHtml(data.business_impact)}</p>`),
renderSection('Playwright Skeleton',`<pre class="code-block"><code>${escapeHtml(data.playwright_skeleton)}</code></pre>`,'code-section')
].join('')}
async function generatePackage(){const attachmentInput=document.getElementById('attachment');const hasAttachment=attachmentInput.files.length>0;const payload={title:document.getElementById('title').value,domain:document.getElementById('domain').value,story:document.getElementById('story').value,criteria:document.getElementById('criteria').value,acceptance_criteria:document.getElementById('criteria').value};const missingFields=validatePayload(payload,hasAttachment);if(missingFields.length){document.getElementById('output').classList.add('output-empty');setStatus(`Please fill in: ${missingFields.join(', ')}`,true);document.getElementById('output').textContent='Validation error: complete all Jira story input fields before generating the QA package.';return}await loadRuntimeConfig();const loadingMessage=runtimeConfig.use_ai?`Fetching analysis from ${formatProviderName(runtimeConfig.provider)} (${getActiveModelLabel()})`:'Generating QA package locally';updateAiSignal(true);startLoadingStatus(loadingMessage);document.getElementById('generateBtn').disabled=true;try{let response;if(hasAttachment){const formData=new FormData();formData.append('title',payload.title);formData.append('domain',payload.domain);formData.append('story',payload.story);formData.append('acceptance_criteria',payload.acceptance_criteria);formData.append('attachment',attachmentInput.files[0]);response=await fetch(ATTACHMENT_API_URL,{method:'POST',body:formData})}else{response=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})}if(!response.ok){if(response.status===422)throw new Error('Please complete all required Jira story fields.');const errorBody=await response.json().catch(()=>null);throw new Error(errorBody?.detail||`API error: ${response.status}`)}const data=await response.json();const output=document.getElementById('output');output.classList.remove('output-empty');output.innerHTML=formatPackage(data);stopLoadingStatus();updateAiSignal(false);setStatus(runtimeConfig.use_ai?`Generated successfully using ${formatProviderName(runtimeConfig.provider)} (${getActiveModelLabel()})`:'Generated successfully using local engine')}catch(error){const output=document.getElementById('output');output.classList.add('output-empty');stopLoadingStatus();updateAiSignal(false);setStatus(error.message.includes('required Jira story fields')||error.message.includes('Unsupported attachment type')||error.message.includes('Attachment is empty')?error.message:'Backend not reachable. Start FastAPI server and try again.',true);output.textContent=error.message.includes('required Jira story fields')||error.message.includes('Unsupported attachment type')||error.message.includes('Attachment is empty')?`Validation error: ${error.message}`:`Error: ${error.message}\n\nRun backend:\ncd backend\npip install -r requirements.txt\nuvicorn app.main:app --reload`}finally{document.getElementById('generateBtn').disabled=false}}
function copyOutput(){navigator.clipboard.writeText(document.getElementById('output').innerText);setStatus('Output copied to clipboard')}
document.getElementById('attachment').addEventListener('change',updateAttachmentPreview);
document.getElementById('previewAttachmentBtn').addEventListener('click',openAttachmentPreview);
document.getElementById('removeAttachmentBtn').addEventListener('click',removeAttachment);
document.getElementById('closePreviewBtn').addEventListener('click',closeAttachmentPreview);
document.getElementById('attachmentPreviewModal').addEventListener('click',event=>{if(event.target.dataset.closePreview==='true'){closeAttachmentPreview()}});
resetAttachmentPreview();
loadRuntimeConfig();
